import { unitArtMarkup } from './evolutionUi';
import type { GameSimulation } from './game/simulation';
import { DRAGON_ITEMS, MAX_ITEM_UPGRADE_LEVEL, SUPER_COST, TOWER_TYPES, TOWER_LABELS, getItemUpgradeChance, getItemUpgradeCost } from './game/superUnits';
import { getUnitDefinition, getUniqueUnitLevel, SUPER_SKILLS } from './game/units';
export function superForgeMarkup(sim: GameSimulation): string {
    return `<span class="dialog-eyebrow">유형별 동시에 1명 · 재료 강화 수치 계승</span><h2 id="dialog-title">유일슈퍼유니크 각성</h2><p class="dialog-description">같은 유형 유니크 1 + 전설 3 + 영웅 3 + 에픽 3 + ${SUPER_COST.toLocaleString()}G</p><div class="super-forge-grid">${TOWER_TYPES.map(type => { const recipe = sim.getSuperRecipe(type), d = getUnitDefinition(`super-${type}`); return `<article class="super-forge-card">${unitArtMarkup(d)}<span>${TOWER_LABELS[type]} · 유일슈퍼유니크</span><h3>${d.name}</h3><p>${SUPER_SKILLS[type]}</p><p>공통 광폭화: 5초간 공격력·공격속도 2배, 종료 후 3초 대기</p><div class="recipe-counts">${(['unique', 'legendary', 'hero', 'epic'] as const).map(key => `<span class="${recipe[key].length >= (key === 'unique' ? 1 : 3) ? 'enough' : ''}">${({ unique: '유니크', legendary: '전설', hero: '영웅', epic: '에픽' })[key]} ${recipe[key].length}/${key === 'unique' ? 1 : 3}</span>`).join('')}</div><button data-craft-super="${type}" ${recipe.ready ? '' : 'disabled'}>${recipe.owned ? '이미 보유 중' : sim.state.gold < SUPER_COST ? `${SUPER_COST.toLocaleString()}G 필요` : '각성 · 10,000G'}</button></article>`; }).join('')}</div><button data-close class="dialog-primary">전장으로 돌아가기</button>`;
}
export function dragonShopMarkup(sim: GameSimulation, slot: number | null, result = ''): string {
    const supers = sim.state.board.map((u, i) => ({ u, i, d: getUnitDefinition(u.definitionId) })).filter(x => x.d.superUnique);
    const selected = supers.find(x => x.i === slot) ?? supers[0];
    const picker = `<div class="super-picker">${supers.map(({ u, i, d }) => `<button data-shop-select="${i}" class="${selected?.i === i ? 'active' : ''}">${d.name} Lv.${getUniqueUnitLevel(sim.meta, u.definitionId)}</button>`).join('')}</div>`;
    if (!selected)
        return `<span class="dialog-eyebrow">슈퍼유니크 전용 · 장비 효과 자동 발동</span><h2 id="dialog-title">드래곤 장비 상점</h2><p class="dialog-description">먼저 각성으로 슈퍼유니크를 만드세요. 각 유닛은 서로 다른 드래곤 장비 3개를 동시에 장착할 수 있습니다.</p><button data-close class="dialog-primary">돌아가기</button>`;
    const { u, i, d } = selected, items = u.items ?? [];
    return `<span class="dialog-eyebrow">보유 ${sim.state.gold.toLocaleString()}G · 장착 즉시 자동 사용</span><h2 id="dialog-title">드래곤 장비 상점</h2>${picker}<div class="inventory-heading"><b>${d.name}</b><span>인벤토리 ${items.length}/3</span></div><div class="inventory-slots">${DRAGON_ITEMS.map(item => { const held = items.find(x => x.kind === item.kind); return `<div class="${held ? 'equipped' : ''}"><span>${item.kind === 'weapon' ? '⚔' : item.kind === 'ring' ? '◈' : '»'}</span><b>${held ? `${item.name} +${held.level}` : '빈 장비 슬롯'}</b></div>`; }).join('')}</div>${result ? `<p class="shop-result" role="status">${result}</p>` : ''}<div class="dragon-items">${DRAGON_ITEMS.map(def => { const item = items.find(x => x.kind === def.kind), level = (item?.level ?? 0) + 1, cost = getItemUpgradeCost(level), chance = getItemUpgradeChance(level) * 100; const value = item ? def.kind === 'weapon' ? `공격력 +${200 + item.bonus}${item.level >= 7 ? ' · 마법 피해 활성' : ''}` : def.kind === 'ring' ? `전체 피해 ${100 + item.bonus} · 발동 10%` : `현재 속도 +${(item.waveSpeedPercent ?? 0) + item.bonus}% (웨이브 ${item.waveSpeedPercent ?? 0}% + 강화 ${item.bonus}%)` : ''; return `<article><div><h3>${def.name}${item ? ` +${item.level}` : ''}</h3><p>${def.description}</p>${item ? `<strong>${value}</strong><small>${item.level >= MAX_ITEM_UPGRADE_LEVEL ? '최대 강화' : `다음 +${level} · 성공 ${Number(chance.toFixed(4))}% · 실패해도 현재 강화 유지`}</small>` : ''}</div><button ${item ? `data-item-upgrade="${def.kind}"` : `data-item-buy="${def.kind}"`} data-shop-slot="${i}" ${item ? item.level >= MAX_ITEM_UPGRADE_LEVEL || sim.state.gold < cost ? 'disabled' : '' : sim.state.gold < def.price ? 'disabled' : ''}>${item ? item.level >= MAX_ITEM_UPGRADE_LEVEL ? `최대 +${MAX_ITEM_UPGRADE_LEVEL}` : `강화 ${cost.toLocaleString()}G` : `구매 ${def.price.toLocaleString()}G`}</button></article>`; }).join('')}</div><p class="dice-footnote">장비 강화 성공률: +1~4 100% · +5~6 66% · +7~8 50% · +9 33%<br>+10~12 20% · +13~15 10% · +16~20 5% · +21~24 2% · 최대 +24<br>+1~3 각 10,000G, +4부터 단계마다 10,000G 증가</p><button data-close class="dialog-primary">전장으로 돌아가기</button>`;
}
